### ISSUE TITLE
Delete Operation in PostgreSQL is not Synced

### ISSUE THREAD

**Issue by zebra-f** [long2ice/meilisync#22]
(Apologies for the second issue in such a short time).

The delete operation doesn't work as expected; it doesn't sync with MeiliSearch. I'm using the [`debezium/postgres`](https://hub.docker.com/r/debezium/postgres/tags) Docker image, which comes with the `wal_level` configured and `wal2json` installed.  
I'm not seeing any logs or errors when performing delete operations.

On the wal2json GitHub page, it mentions:
  
>wal2json is an output plugin for logical decoding. It means that the plugin has access to tuples produced by INSERT and UPDATE. Also, UPDATE/DELETE old row versions can be accessed depending on the configured replica identity.  
  
I'm unsure about what they mean by "old row versions" and how to configure it to work with meilisync, if it's even possible.

By the way debzeium/postgres versions 12 and 14 have no other problems, but with version 15, meilisync throws an error mentioning something like "can't locate pg_wal," if I remember correctly.

**Comment by Pontus-Green** [comment]
I have the same problem

**Comment by christianbradley** [comment]
I also have this issue.

**Comment by xlanex6** [comment]
So I am

**Comment by zebra-f** [comment]
Going back to:  
> On the wal2json GitHub page, it mentions:
>   > wal2json is an output plugin for logical decoding. It means that the plugin has access to tuples produced by INSERT and UPDATE. Also, UPDATE/DELETE old row versions can be accessed depending on the configured replica identity.
 
Configuring replica identity to `FULL` for a table doesn't fix this issue.
