### ISSUE TITLE
meilisync not sync all data from table after first run with empty index in meilisearch

### ISSUE THREAD

**Issue by ThangBuiDuc** [long2ice/meilisync#36]
i just clone dev branch to local and build an image. When i started sync for first time to brand new index, it seem not sync old data from table of postgres but when i updated row and it only sync that row be updated. when refresh, i also face an error meilisync.progress.file.File.set() argument after ** must be a mapping, not str
![image](https://github.com/long2ice/meilisync/assets/111365153/c3b5e2dd-921b-4e48-968a-d8ff4aee39a7)

**Comment by long2ice** [comment]
Try latest
