### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by TheoCouss** [long2ice/meilisync#64]
Once the initial synchronization is completed, this error arises.
I am using the latest version of the dev branch, and my source is MySQL 5.7.
This might be related to issue #18; I really need MySQL 5.7 support.

[2024-01-09 13:31:50.txt](https://github.com/long2ice/meilisync/files/13874454/2024-01-09.13.31.50.txt)

**Comment by long2ice** [comment]
What's the result of `SHOW MASTER STATUS`?

**Comment by TheoCouss** [comment]
It does not return anything, not even a single line.

**Comment by long2ice** [comment]
Did you enable binlog?

**Comment by TheoCouss** [comment]
No problem, I forgot to set a server ID on my MySQL instance. Now it returns this:
![CleanShot 2024-01-09 at 16 36 05](https://github.com/long2ice/meilisync/assets/23056583/6664628f-438d-4d6b-bf80-024bc06a3652)
I still have the same error showing.

**Comment by long2ice** [comment]
Try delete progress in file or redis

**Comment by TheoCouss** [comment]
Thanks for your help earlier! By the way, could you also deploy the updated Docker images? This would really simplify things for everyone, especially considering the issues with version 0.1.2.
