### ISSUE TITLE
ERROR: ModuleNotFoundError: No module named 'motor'

### ISSUE THREAD

**Issue by wbsartori** [long2ice/meilisync#86]
I'm trying to test the synchronization between meilisearch and mysql, at first I followed the documentation with the installation without docker, and when trying to use it, it's giving me this error as if the import wasn't correct. Is this an error in my installation or could there really be a problem in this version?

![image](https://github.com/long2ice/meilisync/assets/25470180/76f57f09-cbdb-416c-9b7b-468659fa4e63)

**Comment by wbsartori** [comment]
Okay, I'm not the best person using Python so I checked and installed all the modules that were reporting errors and everything worked ok, you can close this issue,

**Comment by jyling** [comment]
Incase this is useful for anyone
Here are the packages reported by my machine
`motor`, `asyncmy`
